Test docker compose

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -38,3 +38,26 @@ jobs:
           docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
           docker push berk76/svjis2-app:$TAG
           docker push berk76/svjis2-app:latest
+
+      - name: Start containers
+        run: |
+          docker-compose up -d
+
+      - name: Run basic parametrization
+        run: |
+          docker exec svjis2_app bash "python svjis/manage.py svjis_setup --password changeIt"
+
+      - name: Test of docker-compose
+        run: |
+          string="Dokumenty"
+          if curl -s "http://localhost:8000" | grep -q "$string"; then
+              echo "'$string' found"
+          else
+              echo "'$string' not found"
+              exit 1
+          fi
+
+      - name: Stop containers
+        if: always()
+        run: |
+          docker-compose down
